/// Flutter icons Hosana
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Hosana
///      fonts:
///       - asset: fonts/Hosana.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Hosana {
  Hosana._();

  static const _kFontFam = 'Hosana';
  static const _kFontPkg = null;

  static const IconData bug =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData church =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData award =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pray =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
